title: Dr. Werner Krause's Homepage
logo: /assets/img/Krause_Foto_small.jpg
description: <p>Political Scientist. <br> Research on Comparative Politics, (Radical) Political Parties, and Political Behavior. Passion for Quantitative Methods, Causal Inference, and R.</p>
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
